### ISSUE TITLE
Host redirect problem

### ISSUE THREAD

**Issue by tolstenko** [migueldiaznunez/docker-compose-wso2#10]
First of all, thanks for your effort to expose all config files and settings. I was starting to do the same, but your docker-compose is better.

When I access the API Manager via http://domain:9763/publisher/ it is redirecting me to https://172.20.0.2:9443/publisher/ and it won't work on the remote installation.

Is it possible to inject the domain via env var or something else? Thanks!

![Screen Shot 2019-05-21 at 15 38 08](https://user-images.githubusercontent.com/2386417/58121769-85d81d80-7bde-11e9-888e-79bc559f28d4.png)

**Comment by tolstenko** [comment]
Since I am using google cloud load balancing, I am using http redirection and proxies, I had to change this in order to fix it. https://github.com/tolstenko/docker-compose-wso2/commit/f251cc76d358bb948139b2f16ca1dfb38969024b

**Comment by migueldiaznunez** [comment]
Hello @tolstenko , thanks for your contribution. In my opinion, WSO2 is a customized product and you have to change too many configuration files. If you have to implement your application in a cloud environment, I think that wso2 is not necessary, I would use the products offered by the cloud.
